/**
 * @providesModule ActionTypes
 * @flow
 */


export const SIGNIN = 'SIGNIN';
export const GET_FB_USER_DETAILS = 'GET_FB_USER_DETAILS';
export const GET_LATEST_NEWS = 'GET_LATEST_NEWS';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const UPSERT_USER = 'UPSERT_USER';
export const GET_RESPONSES = 'GET_RESPONSES';
export const LOADING = 'LOADING';
export const GET_MEMBERSHIP_PLANS = 'GET_MEMBERSHIP_PLANS';
export const SET_PAID_USER_STATUS = 'SET_PAID_USER_STATUS';
export const UPGRADE_MEMBERSHIP = 'UPGRADE_MEMBERSHIP';
export const DISMISS_REQUEST_NOTIFICATION = 'DISMISS_REQUEST_NOTIFICATION';
export const HANDLE_REQUEST_NOTIFICATION = 'HANDLE_REQUEST_NOTIFICATION';
export const REPORT_INCIDENT = 'REPORT_INCIDENT';
export const RESPOND_INCIDENT = 'RESPOND_INCIDENT';
export const INCIDENT_IN_PROGRESS = 'INCIDENT_IN_PROGRESS';
export const LOWER_PANEL_OPENED = 'LOWER_PANEL_OPENED';
export const ENABLE_LOCATION = 'ENABLE_LOCATION';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const SWIPED_CARD = 'SWIPED_CARD';
export const SWIPED_CARD_ENDED = 'SWIPED_CARD_ENDED';
export const TOKEN_RETRIEVED = 'TOKEN_RETRIEVED';
export const IS_FIRST_LOAD = 'IS_FIRST_LOAD';


